**Assignment 7**

1.

In [ ]:
import pandas as pd
import numpy as np
import random

In [ ]:
def perceptron(w,X):
    res = X.dot(w)
    if res>=0:
        return 1
    else:
        return 0

def check_convergence(w,P,N):
    for i in P:
        if perceptron(w,i)==0:
            return False
    for i in N:
        if perceptron(w,i)==1:
            return False
    return True


In [ ]:
w=np.random.randint(0,1,3).reshape(3,1)
P=[]
P.append(np.array([1,1,1]))
N=[]
N.append(np.array([1,1,0]))
N.append(np.array([1,0,1]))
N.append(np.array([1,0,0]))
All= P+N
converged=False
while converged == False:
    X = random.choice(All)
    inP=0
    for i in P:
        if np.array_equal(i,X):
            inP=1
            break;
    if inP==1 and perceptron(w,X)==0:
        w = w + X.reshape(3,1)
    if inP==0 and perceptron(w,X)==1:
        w = w - X.reshape(3,1)
    converged = check_convergence(w,P,N)
print("Full Convergence achieved")

Full Convergence achieved


2.

In [ ]:
from sklearn import datasets
from sklearn import preprocessing
import time

wine = datasets.load_wine()
df = pd.DataFrame(wine.data, columns=wine.feature_names)
df['target'] = wine.target
mat=df.to_numpy()
#print(wine.DESCR)
print("Shape of matrix loaded:",mat.shape)
print("Number of Features:",mat.shape[1]-1)
print("Number of Patterns:",mat.shape[0])
print(mat)

Shape of matrix loaded: (178, 14)
Number of Features: 13
Number of Patterns: 178
[[  14.23    1.71    2.43 ...    3.92 1065.      0.  ]
 [  13.2     1.78    2.14 ...    3.4  1050.      0.  ]
 [  13.16    2.36    2.67 ...    3.17 1185.      0.  ]
 ...
 [  13.27    4.28    2.26 ...    1.56  835.      2.  ]
 [  13.17    2.59    2.37 ...    1.62  840.      2.  ]
 [  14.13    4.1     2.74 ...    1.6   560.      2.  ]]


In [ ]:
np.random.shuffle(mat)  
X=mat[:,:-1]

X = preprocessing.normalize(X)
X=np.column_stack((np.ones(X.shape[0]),X))
Y=mat[:,-1]
Y=Y.reshape(mat.shape[0],1)
X=np.column_stack((X,Y))

train_size=int(X.shape[0]*0.4)
X_train,Y_train=X[0:train_size,:],Y[0:train_size,:]
X_test,Y_test=X[train_size:,:],Y[train_size:,:]

print(X)

[[1.         0.0349183  0.0046012  ... 0.00784744 0.96540503 1.        ]
 [1.         0.02953862 0.00761899 ... 0.00680181 0.97580803 1.        ]
 [1.         0.02879519 0.00263044 ... 0.00668086 0.97768616 1.        ]
 ...
 [1.         0.01598664 0.00363333 ... 0.00393806 0.9903745  0.        ]
 [1.         0.03421645 0.00421168 ... 0.00781776 0.96896146 1.        ]
 [1.         0.01987407 0.00473261 ... 0.00264213 0.98717067 2.        ]]


In [ ]:
def sigmoid(X,w):
    x=X.dot(w)
    res = 1/(1+np.exp(-x))
    if res>=0.5:
        return 1
    else:
        return 0
def convergence_status(X,w):
    total = X.shape[0]
    correct=0
    for row in X:
        if sigmoid(row[:-1],w)!=row[-1]:
            correct+=1
    print("Acc ",correct*100.0/total)
    if correct==total:
        return True
    else:
        return False
def train_perceptron(x,w):
    num_samples=x.shape[0]
    converged = False
    while converged==False:
        row = x[random.randint(0,num_samples-1)]
        pred=sigmoid(row[:-1],w)
        if row[-1]==1 and pred==0:
            w+=row[:-1].reshape(row.shape[0]-1,1)
        if row[-1]==0 and pred==1:
            w-=row[:-1].reshape(row.shape[0]-1,1)
        print(w)
        converged=convergence_status(x,w)
    return w

In [ ]:
num_classes=3
w=[np.zeros(X.shape[1]-1).reshape(X.shape[1]-1,1) for i in range(num_classes)]
print(len(w))
for i in range(num_classes):
    x=X_train.copy()
    for row in x:
        if row[-1]==i:
            row[-1]=1
        else:
            row[-1]=0
    w[i]=train_perceptron(x,w[i])
    print("Converged ",i)


3
[[-1.00000000e+00]
 [-2.59977351e-02]
 [-8.25565368e-03]
 [-4.27930673e-03]
 [-4.26037174e-02]
 [-1.66627873e-01]
 [-2.42367815e-03]
 [-8.89944319e-04]
 [-9.84619247e-04]
 [-2.17752333e-03]
 [-1.25349604e-02]
 [-1.47692887e-03]
 [-3.31362246e-03]
 [-9.84619247e-01]]
Acc  29.577464788732396
[[-1.00000000e+00]
 [-2.59977351e-02]
 [-8.25565368e-03]
 [-4.27930673e-03]
 [-4.26037174e-02]
 [-1.66627873e-01]
 [-2.42367815e-03]
 [-8.89944319e-04]
 [-9.84619247e-04]
 [-2.17752333e-03]
 [-1.25349604e-02]
 [-1.47692887e-03]
 [-3.31362246e-03]
 [-9.84619247e-01]]
Acc  29.577464788732396
[[ 0.00000000e+00]
 [-1.27332627e-02]
 [-6.66167984e-03]
 [-2.01418600e-03]
 [-2.80622017e-02]
 [-4.82450200e-02]
 [ 1.86337500e-04]
 [ 1.96242992e-03]
 [-7.23617682e-04]
 [-4.29033953e-05]
 [-7.27764318e-03]
 [-5.07494487e-04]
 [ 3.40399439e-04]
 [ 8.11884709e-03]]


KeyboardInterrupt: ignored