**Part 1**

In [1]:
import numpy as np
import pandas as pd

1.

In [2]:
ten_zeros=np.zeros(10,int)
ten_ones=np.ones(10,int)
ten_fives=np.ones(10,int)*5
print(ten_zeros)
print(ten_ones)
print(ten_fives)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5]


2.

In [3]:
ar=np.arange(11,52,2)
print(ar)

[11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51]


3.

In [4]:
num=np.random.rand()
print(num)
rand_mat = np.random.rand(5,5)
print(rand_mat)

0.8528032115633022
[[0.81539349 0.12416429 0.46746023 0.65419877 0.00872101]
 [0.13554042 0.18065066 0.68242632 0.64337484 0.95190175]
 [0.94161572 0.41923025 0.22840809 0.07003668 0.1960853 ]
 [0.43941968 0.64999673 0.10827045 0.27973067 0.90922689]
 [0.85281622 0.81864459 0.1227923  0.8361532  0.87707522]]


4.

In [5]:
a_file = open("randMat.txt", "w")
for row in rand_mat:
    np.savetxt(a_file, row)
a_file.close()

original_array = np.loadtxt("randMat.txt").reshape(5,5)
print(original_array)

[[0.81539349 0.12416429 0.46746023 0.65419877 0.00872101]
 [0.13554042 0.18065066 0.68242632 0.64337484 0.95190175]
 [0.94161572 0.41923025 0.22840809 0.07003668 0.1960853 ]
 [0.43941968 0.64999673 0.10827045 0.27973067 0.90922689]
 [0.85281622 0.81864459 0.1227923  0.8361532  0.87707522]]


**Part 2**

1.

In [7]:
import matplotlib.image as img
import pandas as pd
from skimage import io


imageMat = img.imread('/content/drive/MyDrive/Other-Material/Doom eternal.jpg')
print("Image shape:",
	imageMat.shape)

if(imageMat.shape[2] == 3):
  imageMat_reshape = imageMat.reshape(imageMat.shape[0],-1)
  print("Reshaping to 2D array:",
		imageMat_reshape.shape)

else:
  imageMat_reshape = imageMat
	
print("shape of image saved :",
	imageMat_reshape.shape)

mat_df = pd.DataFrame(imageMat_reshape)
mat_df.to_csv('doomsave.csv',
			header = None,
			index = None)




Image shape: (1080, 1920, 3)
Reshaping to 2D array: (1080, 5760)
shape of image saved : (1080, 5760)


2.

In [8]:
df= pd.read_csv('doomsave.csv',header=None).iloc[:-1,:-1]
loaded_mat=df.values
print("Image shape of loaded Image :",
	loaded_mat.shape)

Image shape of loaded Image : (1079, 5759)


In [9]:
loaded_df = pd.read_csv('doomsave.csv',
						sep = ',',
						header = None)
loaded_mat = loaded_df.values

loaded_mat=np.delete(loaded_mat,[-1],0)
loaded_mat=np.delete(loaded_mat,[-1],1)
print("Image shape of loaded Image :",
	loaded_mat.shape)


Image shape of loaded Image : (1079, 5759)


3.

In [10]:
today = pd.to_datetime("today").strftime("%m/%d/%Y")
print(today)

08/17/2021


**Part 3**

1.

In [11]:
from datetime import date
print("enter birth date and current date (space separated)in dd/mm/yyyy")
A=input().split(' ')
bd=A[0].split('/')
cd=A[1].split('/')
today = date(int(cd[2]),int(cd[1]),int(cd[0]))
born=date(int(bd[2]),int(bd[1]),int(bd[0]))
try:
  birthday = born.replace(year = today.year)
except ValueError:
   birthday = born.replace(year = today.year,
                month = born.month + 1, day = 1) 
if birthday > today:
  print(today.year - born.year - 1,' years')
else:
  print(today.year - born.year,' years')

		


enter birth date and current date (space separated)in dd/mm/yyyy
12/12/2012 12/09/2031
18  years
